### ISSUE TITLE
[jsk_data] KeyError: 'config'

### ISSUE THREAD

**Issue by garaemon** [jsk-ros-pkg/jsk_common#1137]
```
$ jsk_data  
Traceback (most recent call last):
  File "/home/lueda/ros/hydro/devel/bin/jsk_data", line 5, in <module>
    exec(fh.read())
  File "<string>", line 4, in <module>
  File "/home/lueda/ros/hydro/src/jsk-ros-pkg/jsk_common/jsk_data/src/jsk_data/cli.py", line 29, in <module>
    LOGIN_USER = _get_login_user(host=HOST)
  File "/home/lueda/ros/hydro/src/jsk-ros-pkg/jsk_common/jsk_data/src/jsk_data/cli.py", line 21, in _get_login_user
    username = get_user_by_hostname(host)
  File "/home/lueda/ros/hydro/src/jsk-ros-pkg/jsk_common/jsk_data/src/jsk_data/ssh.py", line 29, in get_user_by_hostname
    config = entry['config']
KeyError: 'config'
```

**Comment by wkentaro** [comment]
Should be fixed by #1138
