### ISSUE TITLE
jsk_rosbag_tools build error in noetic

### ISSUE THREAD

**Issue by knorth55** [jsk-ros-pkg/jsk_common#1780]
```
2023-03-20T08:23:51.3188503Z [jsk_rosbag_tools:make] Traceback (most recent call last):
2023-03-20T08:23:51.3188712Z 
2023-03-20T08:23:51.3188718Z 
2023-03-20T08:23:51.3188855Z                                                                                 
2023-03-20T08:23:51.3189314Z [jsk_rosbag_tools:make]   File "/github/home/ros/ws_jsk_common/src/jsk_common/jsk_rosbag_tools/scripts/bag_to_video.py", line 6, in <module>
2023-03-20T08:23:51.3189627Z 
2023-03-20T08:23:51.3189633Z 
2023-03-20T08:23:51.3189770Z                                                                                 
2023-03-20T08:23:51.3190136Z [jsk_rosbag_tools:make]     from jsk_rosbag_tools.bag_to_video import bag_to_video
2023-03-20T08:23:51.3190380Z 
2023-03-20T08:23:51.3190386Z 
2023-03-20T08:23:51.3190519Z                                                                                 
2023-03-20T08:23:51.3190991Z [jsk_rosbag_tools:make]   File "/github/home/ros/ws_jsk_common/src/jsk_common/jsk_rosbag_tools/python/jsk_rosbag_tools/bag_to_video.py", line 13, in <module>
2023-03-20T08:23:51.3191327Z 
2023-03-20T08:23:51.3191333Z 
2023-03-20T08:23:51.3191467Z                                                                                 
2023-03-20T08:23:51.3191821Z [jsk_rosbag_tools:make]     from jsk_rosbag_tools.bag_to_audio import bag_to_audio
2023-03-20T08:23:51.3192062Z 
2023-03-20T08:23:51.3192068Z 
2023-03-20T08:23:51.3192203Z                                                                                 
2023-03-20T08:23:51.3192675Z [jsk_rosbag_tools:make]   File "/github/home/ros/ws_jsk_common/src/jsk_common/jsk_rosbag_tools/python/jsk_rosbag_tools/bag_to_audio.py", line 6, in <module>
2023-03-20T08:23:51.3193002Z 
2023-03-20T08:23:51.3193008Z 
2023-03-20T08:23:51.3193141Z                                                                                 
2023-03-20T08:23:51.3193509Z [jsk_rosbag_tools:make]     from scipy.io.wavfile import write as wav_write
2023-03-20T08:23:51.3193741Z 
2023-03-20T08:23:51.3193748Z 
2023-03-20T08:23:51.3193880Z                                                                                 
2023-03-20T08:23:51.3194416Z [jsk_rosbag_tools:make]   File "/usr/lib/python3/dist-packages/scipy/io/__init__.py", line 97, in <module>
2023-03-20T08:23:51.3194691Z 
2023-03-20T08:23:51.3194696Z 
2023-03-20T08:23:51.3194832Z                                                                                 
2023-03-20T08:23:51.3195220Z [jsk_rosbag_tools:make]     from .matlab import loadmat, savemat, whosmat, byteordercodes
2023-03-20T08:23:51.3195463Z 
2023-03-20T08:23:51.3195490Z 
2023-03-20T08:23:51.3195617Z                                                                                 
2023-03-20T08:23:51.3196161Z [jsk_rosbag_tools:make]   File "/usr/lib/python3/dist-packages/scipy/io/matlab/__init__.py", line 13, in <module>
2023-03-20T08:23:51.3196443Z 
2023-03-20T08:23:51.3196449Z 
2023-03-20T08:23:51.3196584Z                                                                                 
2023-03-20T08:23:51.3197066Z [jsk_rosbag_tools:make]     from .mio import loadmat, savemat, whosmat
2023-03-20T08:23:51.3197294Z 
2023-03-20T08:23:51.3197300Z 
2023-03-20T08:23:51.3197421Z                                                                                 
2023-03-20T08:23:51.3197965Z [jsk_rosbag_tools:make]   File "/usr/lib/python3/dist-packages/scipy/io/matlab/mio.py", line 11, in <module>
2023-03-20T08:23:51.3198243Z 
2023-03-20T08:23:51.3198249Z 
2023-03-20T08:23:51.3198385Z                                                                                 
2023-03-20T08:23:51.3198876Z [jsk_rosbag_tools:make]     from .mio4 import MatFile4Reader, MatFile4Writer
2023-03-20T08:23:51.3199122Z 
2023-03-20T08:23:51.3199128Z 
2023-03-20T08:23:51.3199249Z                                                                                 
2023-03-20T08:23:51.3199794Z [jsk_rosbag_tools:make]   File "/usr/lib/python3/dist-packages/scipy/io/matlab/mio4.py", line 11, in <module>
2023-03-20T08:23:51.3200084Z 
2023-03-20T08:23:51.3200089Z 
2023-03-20T08:23:51.3200228Z                                                                                 
2023-03-20T08:23:51.3200556Z [jsk_rosbag_tools:make]     import scipy.sparse
2023-03-20T08:23:51.3200844Z 
2023-03-20T08:23:51.3200849Z 
2023-03-20T08:23:51.3200973Z                                                                                 
2023-03-20T08:23:51.3201581Z [jsk_rosbag_tools:make]   File "/usr/lib/python3/dist-packages/scipy/sparse/__init__.py", line 229, in <module>
2023-03-20T08:23:51.3202051Z 
2023-03-20T08:23:51.3202057Z 
2023-03-20T08:23:51.3202261Z                                                                                 
2023-03-20T08:23:51.3202666Z [jsk_rosbag_tools:make]     from .base import *
2023-03-20T08:23:51.3202902Z 
2023-03-20T08:23:51.3202908Z 
2023-03-20T08:23:51.3203090Z                                                                                 
2023-03-20T08:23:51.3203655Z [jsk_rosbag_tools:make]   File "/usr/lib/python3/dist-packages/scipy/sparse/base.py", line 8, in <module>
2023-03-20T08:23:51.3203977Z 
2023-03-20T08:23:51.3203983Z 
2023-03-20T08:23:51.3204223Z                                                                                 
2023-03-20T08:23:51.3204749Z [jsk_rosbag_tools:make]     from .sputils import (isdense, isscalarlike, isintlike,
2023-03-20T08:23:51.3205042Z 
2023-03-20T08:23:51.3205048Z 
2023-03-20T08:23:51.3205226Z                                                                                 
2023-03-20T08:23:51.3205798Z [jsk_rosbag_tools:make]   File "/usr/lib/python3/dist-packages/scipy/sparse/sputils.py", line 16, in <module>
2023-03-20T08:23:51.3206129Z 
2023-03-20T08:23:51.3206135Z 
2023-03-20T08:23:51.3206313Z                                                                                 
2023-03-20T08:23:51.3206840Z [jsk_rosbag_tools:make]     supported_dtypes = [np.typeDict[x] for x in supported_dtypes]
2023-03-20T08:23:51.3207140Z 
2023-03-20T08:23:51.3207152Z 
2023-03-20T08:23:51.3207329Z                                                                                 
2023-03-20T08:23:51.3207911Z [jsk_rosbag_tools:make]   File "/usr/lib/python3/dist-packages/scipy/sparse/sputils.py", line 16, in <listcomp>
2023-03-20T08:23:51.3208241Z 
2023-03-20T08:23:51.3208247Z 
2023-03-20T08:23:51.3208425Z                                                                                 
2023-03-20T08:23:51.3208949Z [jsk_rosbag_tools:make]     supported_dtypes = [np.typeDict[x] for x in supported_dtypes]
2023-03-20T08:23:51.3209249Z 
2023-03-20T08:23:51.3209255Z 
2023-03-20T08:23:51.3209442Z                                                                                 
2023-03-20T08:23:51.3210212Z [jsk_rosbag_tools:make]   File "/github/home/ros/ws_jsk_common/devel/.private/jsk_rosbag_tools/share/jsk_rosbag_tools/venv/lib/python3.8/site-packages/numpy/__init__.py", line 320, in __getattr__
2023-03-20T08:23:51.3210645Z 
2023-03-20T08:23:51.3210651Z 
2023-03-20T08:23:51.3210976Z                                                                                 
2023-03-20T08:23:51.3211448Z [jsk_rosbag_tools:make]     raise AttributeError("module {!r} has no attribute "
2023-03-20T08:23:51.3211768Z 
2023-03-20T08:23:51.3211773Z 
2023-03-20T08:23:51.3211952Z                                                                                 
2023-03-20T08:23:51.3212757Z [jsk_rosbag_tools:make] AttributeError: module 'numpy' has no attribute 'typeDict'
2023-03-20T08:23:51.3212998Z 
2023-03-20T08:23:51.3213004Z 
2023-03-20T08:23:51.3213184Z                                                                                 
2023-03-20T08:23:51.3213761Z [jsk_rosbag_tools:make] Traceback (most recent call last):
2023-03-20T08:23:51.3214023Z 
2023-03-20T08:23:51.3214244Z                                                                                 
2023-03-20T08:23:51.3214794Z [jsk_rosbag_tools:make]   File "/github/home/ros/ws_jsk_common/src/jsk_common/jsk_rosbag_tools/scripts/bag_to_video.py", line 6, in <module>
2023-03-20T08:23:51.3215098Z 
2023-03-20T08:23:51.3215280Z                                                                                 
2023-03-20T08:23:51.3215753Z [jsk_rosbag_tools:make]     from jsk_rosbag_tools.bag_to_video import bag_to_video
2023-03-20T08:23:51.3216041Z 
2023-03-20T08:23:51.3216333Z                                                                                 
2023-03-20T08:23:51.3216951Z [jsk_rosbag_tools:make]   File "/github/home/ros/ws_jsk_common/src/jsk_common/jsk_rosbag_tools/python/jsk_rosbag_tools/bag_to_video.py", line 13, in <module>
2023-03-20T08:23:51.3217266Z 
2023-03-20T08:23:51.3217272Z 
2023-03-20T08:23:51.3217476Z                                                                                 
2023-03-20T08:23:51.3217932Z [jsk_rosbag_tools:make]     from jsk_rosbag_tools.bag_to_audio import bag_to_audio
2023-03-20T08:23:51.3268216Z 
2023-03-20T08:23:51.3268369Z                                                                                 
2023-03-20T08:23:51.3268892Z [jsk_rosbag_tools:make]   File "/github/home/ros/ws_jsk_common/src/jsk_common/jsk_rosbag_tools/python/jsk_rosbag_tools/bag_to_audio.py", line 6, in <module>
2023-03-20T08:23:51.3269223Z 
2023-03-20T08:23:51.3269355Z                                                                                 
2023-03-20T08:23:51.3269707Z [jsk_rosbag_tools:make]     from scipy.io.wavfile import write as wav_write
2023-03-20T08:23:51.3269942Z 
2023-03-20T08:23:51.3270071Z                                                                                 
2023-03-20T08:23:51.3270698Z [jsk_rosbag_tools:make]   File "/usr/lib/python3/dist-packages/scipy/io/__init__.py", line 97, in <module>
2023-03-20T08:23:51.3270965Z 
2023-03-20T08:23:51.3270972Z 
2023-03-20T08:23:51.3271108Z                                                                                 
2023-03-20T08:23:51.3271471Z [jsk_rosbag_tools:make]     from .matlab import loadmat, savemat, whosmat, byteordercodes
2023-03-20T08:23:51.3271727Z 
2023-03-20T08:23:51.3271855Z                                                                                 
2023-03-20T08:23:51.3272446Z [jsk_rosbag_tools:make]   File "/usr/lib/python3/dist-packages/scipy/io/matlab/__init__.py", line 13, in <module>
2023-03-20T08:23:51.3272727Z 
2023-03-20T08:23:51.3272733Z 
2023-03-20T08:23:51.3272863Z                                                                                 
2023-03-20T08:23:51.3273196Z [jsk_rosbag_tools:make]     from .mio import loadmat, savemat, whosmat
2023-03-20T08:23:51.3273412Z 
2023-03-20T08:23:51.3273419Z 
2023-03-20T08:23:51.3273550Z                                                                                 
2023-03-20T08:23:51.3274065Z [jsk_rosbag_tools:make]   File "/usr/lib/python3/dist-packages/scipy/io/matlab/mio.py", line 11, in <module>
2023-03-20T08:23:51.3274333Z 
2023-03-20T08:23:51.3274339Z 
2023-03-20T08:23:51.3274463Z                                                                                 
2023-03-20T08:23:51.3275114Z [jsk_rosbag_tools:make]     from .mio4 import MatFile4Reader, MatFile4Writer
2023-03-20T08:23:51.3275345Z 
2023-03-20T08:23:51.3275474Z                                                                                 
2023-03-20T08:23:51.3276002Z [jsk_rosbag_tools:make]   File "/usr/lib/python3/dist-packages/scipy/io/matlab/mio4.py", line 11, in <module>
2023-03-20T08:23:51.3276271Z 
2023-03-20T08:23:51.3276277Z 
2023-03-20T08:23:51.3276404Z                                                                                 
2023-03-20T08:23:51.3276702Z [jsk_rosbag_tools:make]     import scipy.sparse
2023-03-20T08:23:51.3276889Z 
2023-03-20T08:23:51.3276894Z 
2023-03-20T08:23:51.3277172Z                                                                                 
2023-03-20T08:23:51.3277703Z [jsk_rosbag_tools:make]   File "/usr/lib/python3/dist-packages/scipy/sparse/__init__.py", line 229, in <module>
2023-03-20T08:23:51.3277970Z 
2023-03-20T08:23:51.3277976Z 
2023-03-20T08:23:51.3278102Z                                                                                 
2023-03-20T08:23:51.3278400Z [jsk_rosbag_tools:make]     from .base import *
2023-03-20T08:23:51.3278576Z 
2023-03-20T08:23:51.3278581Z 
2023-03-20T08:23:51.3278706Z                                                                                 
2023-03-20T08:23:51.3279215Z [jsk_rosbag_tools:make]   File "/usr/lib/python3/dist-packages/scipy/sparse/base.py", line 8, in <module>
2023-03-20T08:23:51.3279482Z 
2023-03-20T08:23:51.3279488Z 
2023-03-20T08:23:51.3279612Z                                                                                 
2023-03-20T08:23:51.3279978Z [jsk_rosbag_tools:make]     from .sputils import (isdense, isscalarlike, isintlike,
2023-03-20T08:23:51.3280211Z 
2023-03-20T08:23:51.3280217Z 
2023-03-20T08:23:51.3280342Z                                                                                 
2023-03-20T08:23:51.3280859Z [jsk_rosbag_tools:make]   File "/usr/lib/python3/dist-packages/scipy/sparse/sputils.py", line 16, in <module>
2023-03-20T08:23:51.3281140Z 
2023-03-20T08:23:51.3281145Z 
2023-03-20T08:23:51.3281269Z                                                                                 
2023-03-20T08:23:51.3281631Z [jsk_rosbag_tools:make]     supported_dtypes = [np.typeDict[x] for x in supported_dtypes]
2023-03-20T08:23:51.3281872Z 
2023-03-20T08:23:51.3281882Z 
2023-03-20T08:23:51.3282002Z                                                                                 
2023-03-20T08:23:51.3282530Z [jsk_rosbag_tools:make]   File "/usr/lib/python3/dist-packages/scipy/sparse/sputils.py", line 16, in <listcomp>
2023-03-20T08:23:51.3282805Z 
2023-03-20T08:23:51.3282810Z 
2023-03-20T08:23:51.3282942Z                                                                                 
2023-03-20T08:23:51.3283301Z [jsk_rosbag_tools:make]     supported_dtypes = [np.typeDict[x] for x in supported_dtypes]
2023-03-20T08:23:51.3283546Z 
2023-03-20T08:23:51.3283552Z 
2023-03-20T08:23:51.3283672Z                                                                                 
2023-03-20T08:23:51.3284388Z [jsk_rosbag_tools:make]   File "/github/home/ros/ws_jsk_common/devel/.private/jsk_rosbag_tools/share/jsk_rosbag_tools/venv/lib/python3.8/site-packages/numpy/__init__.py", line 320, in __getattr__
2023-03-20T08:23:51.3284760Z 
2023-03-20T08:23:51.3284766Z 
2023-03-20T08:23:51.3284890Z                                                                                 
2023-03-20T08:23:51.3285237Z [jsk_rosbag_tools:make]     raise AttributeError("module {!r} has no attribute "
2023-03-20T08:23:51.3285466Z 
2023-03-20T08:23:51.3285472Z 
2023-03-20T08:23:51.3285604Z                                                                                 
2023-03-20T08:23:51.3286058Z [jsk_rosbag_tools:make] AttributeError: module 'numpy' has no attribute 'typeDict'
2023-03-20T08:23:51.3286308Z 
```

**Comment by k-okada** [comment]
should be fixed.
