### ISSUE TITLE
somethign wrong on moviepy on 22.04

### ISSUE THREAD

**Issue by k-okada** [jsk-ros-pkg/jsk_common#1798]
https://github.com/jsk-ros-pkg/jsk_common/actions/runs/8505002970/job/23324698471?pr=1797
```
[ 40%] Lock input requirements if they don't exist
cd /github/home/ws_current/src/jsk_common/jsk_rosbag_tools && /github/home/ws_current/build_isolated/jsk_rosbag_tools/catkin_generated/env_cached.sh rosrun catkin_virtualenv venv_lock /github/home/ws_current/build_isolated/jsk_rosbag_tools/venv --package-name jsk_rosbag_tools --input-requirements requirements.in --no-overwrite --extra-pip-args \"-qq\ --retries\ 10\ --timeout\ 30\"
    WARNING: Generating metadata for package pillow produced metadata for project name unknown. Fix your #egg=pillow fragments.
Traceback (most recent call last):
  File "/github/home/ws_current/build_isolated/jsk_rosbag_tools/venv/bin/pip-compile", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/github/home/ws_current/build_isolated/jsk_rosbag_tools/venv/lib/python3.10/site-packages/piptools/scripts/compile.py", line 392, in cli
    results = resolver.resolve(max_rounds=max_rounds)
  File "/github/home/ws_current/build_isolated/jsk_rosbag_tools/venv/lib/python3.10/site-packages/piptools/resolver.py", line 169, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/github/home/ws_current/build_isolated/jsk_rosbag_tools/venv/lib/python3.10/site-packages/piptools/resolver.py", line 274, in _resolve_one_round
    their_constraints.extend(self._iter_dependencies(best_match))
  File "/github/home/ws_current/build_isolated/jsk_rosbag_tools/venv/lib/python3.10/site-packages/piptools/resolver.py", line 381, in _iter_dependencies
    self.dependency_cache[ireq] = sorted(str(ireq.req) for ireq in dependencies)
  File "/github/home/ws_current/build_isolated/jsk_rosbag_tools/venv/lib/python3.10/site-packages/piptools/cache.py", line 128, in __setitem__
    pkgname, pkgversion_and_extras = self.as_cache_key(ireq)
  File "/github/home/ws_current/build_isolated/jsk_rosbag_tools/venv/lib/python3.10/site-packages/piptools/cache.py", line 95, in as_cache_key
    name, version, extras = as_tuple(ireq)
  File "/github/home/ws_current/build_isolated/jsk_rosbag_tools/venv/lib/python3.10/site-packages/piptools/utils.py", line 139, in as_tuple
    raise TypeError("Expected a pinned InstallRequirement, got {}".format(ireq))
TypeError: Expected a pinned InstallRequirement, got unknown from https://files.pythonhosted.org/packages/ef/43/c50c17c5f7d438e836c169e343695534c38c77f60e7c90389bd77981bc21/pillow-10.3.0.tar.gz#sha256=9d2455fbf44c914840c793e89aa82d0e1763a14253a000743719ae5946814b2d (from imageio==2.34.0->moviepy==1.0.3->-r requirements.in (line 1))
Traceback (most recent call last):
  File "/github/home/ws_depend/devel_isolated/catkin_virtualenv/lib/catkin_virtualenv/venv_lock", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/github/home/ws_depend/src/catkin_virtualenv/scripts/venv_lock", line 47, in <module>
    venv.lock(
  File "/github/home/ws_depend/src/catkin_virtualenv/src/catkin_virtualenv/venv.py", line 143, in lock
    run_command(command, check=True)
  File "<string>", line 44, in run_command
```

**Comment by iory** [comment]
#1799 could be resolve this problem.
