### ISSUE TITLE
jskrosbuild fails to build euslisp

### ISSUE THREAD

**Issue by otsubo** [jsk-ros-pkg/jsk_common#795]
````
(...snip...)
+ cd /home/otsubo/ros/hydro_parent/src
+ wget https://raw.github.com/jsk-ros-pkg/jsk_travis/master/rosdep-install.sh -O -
+ ROS_DISTRO=hydro
+ bash
--2015-02-20 22:38:58--  https://raw.github.com/jsk-ros-pkg/jsk_travis/master/rosdep-install.sh
Resolving raw.github.com (raw.github.com)... 103.245.222.133
Connecting to raw.github.com (raw.github.com)|103.245.222.133|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://raw.githubusercontent.com/jsk-ros-pkg/jsk_travis/master/rosdep-install.sh [following]
--2015-02-20 22:39:01--  https://raw.githubusercontent.com/jsk-ros-pkg/jsk_travis/master/rosdep-install.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 103.245.222.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|103.245.222.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 563 [text/plain]
Saving to: `STDOUT'

100%[=============================================================>] 563         --.-K/s   in 0s      

2015-02-20 22:39:01 (17.5 MB/s) - written to stdout [563/563]


ERROR: Rosdep experienced an error: Invalid package manifest "/home/otsubo/ros/hydro_parent/src/euslisp/package.xml": Package version ":{version}" does not follow version conventions
Please go to the rosdep page [1] and file a bug report with the stack trace below.
[1] : http://www.ros.org/wiki/rosdep

rosdep version: 0.11.1

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/rosdep2/main.py", line 136, in rosdep_main
    exit_code = _rosdep_main(args)
  File "/usr/lib/python2.7/dist-packages/rosdep2/main.py", line 345, in _rosdep_main
    return _package_args_handler(command, parser, options, args)
  File "/usr/lib/python2.7/dist-packages/rosdep2/main.py", line 394, in _package_args_handler
    pkgs = find_catkin_packages_in(path, options.verbose)
  File "/usr/lib/python2.7/dist-packages/rosdep2/catkin_packages.py", line 33, in find_catkin_packages_in
    packages = find_packages(path)
  File "/usr/lib/python2.7/dist-packages/catkin_pkg/packages.py", line 83, in find_packages
    packages = find_packages_allowing_duplicates(basepath, exclude_paths=exclude_paths, exclude_subspaces=exclude_subspaces)
  File "/usr/lib/python2.7/dist-packages/catkin_pkg/packages.py", line 109, in find_packages_allowing_duplicates
    packages[path] = parse_package(os.path.join(basepath, path))
  File "/usr/lib/python2.7/dist-packages/catkin_pkg/package.py", line 360, in parse_package
    return parse_package_string(f.read(), filename)
  File "/usr/lib/python2.7/dist-packages/catkin_pkg/package.py", line 532, in parse_package_string
    pkg.validate()
  File "/usr/lib/python2.7/dist-packages/catkin_pkg/package.py", line 235, in validate
    raise InvalidPackage('\n'.join(errors))
InvalidPackage: Invalid package manifest "/home/otsubo/ros/hydro_parent/src/euslisp/package.xml": Package version ":{version}" does not follow version conventions
````
after i replace the string to 9.1.0, it starts to work.

According to this commit, 
https://github.com/tork-a/euslisp-release/commit/c29d6deb6c645e44f013d67b2f15c8f0f8beabde

@k-okada replaced the version string to :{version} somehow... why?

mention: @ompugao

**Comment by k-okada** [comment]
please use latest version of jsk_roseus
https://github.com/jsk-ros-pkg/jsk_roseus/pull/243

--
◉ Kei Okada
